root: ./docs/

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  getting-started: getting-started/installation.md
  configuration: configuration/basic.md
  clustering: clustering/overview.md
